### ISSUE TITLE
Server verify failed

### ISSUE THREAD

**Issue by Leechen2014** [sitewhere/sitewhere-android-sdk#2]
when i run this  demo it shows thant  'Server verify failed unable to connect to sever ' , what should i do ?

**Comment by johnykary** [comment]
I have the same problem ,i put the ip address and port 8080 of my pc to the application but i got the same message

**Comment by johnykary** [comment]
fixed it! 
just uncomment everything in build gradle of sitewhere android sdk

**Comment by derekadams** [comment]
I'll add leave this open so we can go back and fix the code for the next release. Thanks for tracking down the solution!

**Comment by scShan** [comment]
SameProblem Server verify failed. the logcat is below. How to fix? it said " can not  find class SiteWhereServer
-------------------------------------
906 4789-4789/com.sitewhere.android.example E/SiteWhereConnectivity: Unable to connect to server.
                                                                                    com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of java.lang.Class, problem: Didn't find class "com.sitewhere.server.SiteWhereServer" on path: DexPathList[[zip file "/data/app/com.sitewhere.android.example-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.sitewhere.android.example-1, /vendor/lib, /system/lib]]
                                                                                        at [Source: org.apache.http.conn.EofSensorInputStream@acfbc080; line: 1, column: 2] (through reference chain: com.sitewhere.rest.model.system.Version["serverClass"])
                                                                                        at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:594)
                                                                                        at com.fasterxml.jackson.databind.deser.std.ClassDeserializer.deserialize(ClassDeserializer.java:32)
                                                                                        at com.fasterxml.jackson.databind.deser.std.ClassDeserializer.deserialize(ClassDeserializer.java:11)
                                                                                        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:449)
                                                                                        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:98)
                                                                                        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)
                                                                                        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
                                                                                        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2888)
                                                                                        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2094)
                                                                                        at org.springframework.http.converter.json.MappingJackson2HttpMessageConverter.readInternal(MappingJackson2HttpMessageConverter.java:123)
                                                                                        at org.springframework.http.converter.AbstractHttpMessageConverter.read(AbstractHttpMessageConverter.java:147)
                                                                                        at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:76)
                                                                                        at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:655)
                                                                                        at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:641)
                                                                                        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:484)
                                                                                        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:447)
                                                                                        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:422)
                                                                                        at com.sitewhere.rest.client.SiteWhereClient.sendRest(SiteWhereClient.java:1017)
                                                                                        at com.sitewhere.rest.client.SiteWhereClient.getSiteWhereVersion(SiteWhereClient.java:200)
                                                                                        at com.sitewhere.android.example.ConnectivityWizardFragment$HostVerifier.run(ConnectivityWizardFragment.java:479)
                                                                                        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                        at java.lang.Thread.run(Thread.java:841)
                                                                                     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.sitewhere.server.SiteWhereServer" on path: DexPathList[[zip file "/data/app/com.sitewhere.android.example-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.sitewhere.android.example-1, /vendor/lib, /system/lib]]
                                                                                        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                                                        at java.lang.Class.classForName(Native Method)
                                                                                        at java.lang.Class.forName(Class.java:251)
                                                                                        at com.fasterxml.jackson.databind.util.ClassUtil.findClass(ClassUtil.java:230)
                                                                                        at com.fasterxml.jackson.databind.DeserializationContext.findClass(DeserializationContext.java:394)
                                                                                        at com.fasterxml.jackson.databind.deser.std.ClassDeserializer.deserialize(C

**Comment by scShan** [comment]
public void run() {
						handleVerifyError("SiteWhere version call failed.", e);
					}
				});
			} catch (final RuntimeException e) {
				getActivity().runOnUiThread(new Runnable() {

					@Override
					public void run() {
						handleVerifyError("#  Unable to connect to server._ // Verify StopHere a Runtime Exception", e.getCause());
					}
				});

**Comment by scShan** [comment]
Solution: to remove the comment line "//" in build.gradle file of sitewhere android and close the project in android studio,
then open again and run build.
