### ISSUE TITLE
Exception obtaining JWT

### ISSUE THREAD

**Issue by 15510101913** [sitewhere/sitewhere-android-sdk#8]
after when i use ISiteWhereClient initialized , Futere<ISiteWhereClient>.get() code throws an exception.
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802) 
     Caused by: java.util.concurrent.ExecutionException: com.sitewhere.spi.SiteWhereException: Exception obtaining JWT.
        at java.util.concurrent.FutureTask.report(FutureTask.java:94)
        at java.util.concurrent.FutureTask.get(FutureTask.java:164)
        at com.zt.ztadvertisement.activity.newAct.SmallMainActivity.sitWhereLogin(SmallMainActivity.kt:454)
        at com.zt.ztadvertisement.activity.newAct.SmallMainActivity.access$sitWhereLogin(SmallMainActivity.kt:49)
        at com.zt.ztadvertisement.activity.newAct.SmallMainActivity$onMQTTServiceReady$1.run(SmallMainActivity.kt:340)
        at android.os.Handler.handleCallback(Handler.java:755)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6141)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802) 
     Caused by: com.sitewhere.spi.SiteWhereException: Exception obtaining JWT.
        at com.sitewhere.rest.client.SiteWhereClient.initialize(SiteWhereClient.java:556)
        at com.zt.ztadvertisement.activity.newAct.SmallMainActivity$SiteWhereClientConnector.call(SmallMainActivity.kt:590)
        at com.zt.ztadvertisement.activity.newAct.SmallMainActivity$SiteWhereClientConnector.call(SmallMainActivity.kt:579)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.net.UnknownHostException: Unable to resolve host "iot.dtznjg.com": No address associated with hostname
        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:125)
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:74)
        at java.net.InetAddress.getAllByName(InetAddress.java:752)
        at okhttp3.Dns$1.lookup(Dns.java:40)
        at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
        at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
        at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:214)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.sitewhere.rest.client.SiteWhereClient$1.intercept(SiteWhereClient.java:575)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
        at okhttp3.RealCall.execute(RealCall.java:92)
    	at retrofit2.OkHttpCall.execute(OkHttpCall.

**Comment by 15510101913** [comment]
When can you fix this bug?

**Comment by 15510101913** [comment]
When can you fix this bug? @derekadams

**Comment by derekadams** [comment]
We are in the process of releasing SiteWhere CE 2.1 right now, but once that is done, we will take a look at the Android SDK and fix the bug. Thanks!
